//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Tbl_Musterı
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Musterı()
        {
            this.Tbl_Satıs = new HashSet<Tbl_Satıs>();
        }
    
        public int Musteriİd { get; set; }
        [Required(ErrorMessage ="Bu alanı Boş Bırakamazsınız")]
        [StringLength(50,ErrorMessage ="En Fazla %0 Karakterlik İsim Girin")]
        public string MusteriAd { get; set; }
        [Required(ErrorMessage = "Bu alanı Boş Bırakamazsınız")]
        [StringLength(50, ErrorMessage = "En Fazla %0 Karakterlik İsim Girin")]
        public string MusteriSoyad { get; set; }
        public string Sehir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Satıs> Tbl_Satıs { get; set; }
    }
}
